const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.JavaScriptInEvents.Folhaglobal_Event4_Act2,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying
	];
};
self.C3_JsPropNameTable = [
	{Âncora: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sprite5: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{Atirador: 0},
	{Sólido: 0},
	{Piso: 0},
	{VidaZumbi: 0},
	{zumbi2: 0},
	{Teclado: 0},
	{Mouse: 0},
	{Projétil: 0},
	{DestruirExternamente: 0},
	{balaMapa: 0},
	{Sprite4: 0},
	{GameOver: 0},
	{Sprite9: 0},
	{Inicio: 0},
	{BalaEdição: 0},
	{ZumbiDaMorte: 0},
	{Sprite3: 0},
	{Chegada: 0},
	{FogoDaMorte: 0},
	{Texto3: 0},
	{Sprite2: 0},
	{Áudio: 0},
	{Sprite6: 0},
	{Texto5: 0},
	{Texto6: 0},
	{Texto: 0},
	{Texto2: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Texto4: 0},
	{Sprite12: 0}
];

self.InstanceType = {
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Atirador: class extends self.ISpriteInstance {},
	Piso: class extends self.ISpriteInstance {},
	zumbi2: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	balaMapa: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	GameOver: class extends self.ISpriteFontInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Inicio: class extends self.ISpriteFontInstance {},
	BalaEdição: class extends self.ISpriteInstance {},
	ZumbiDaMorte: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Chegada: class extends self.ISpriteInstance {},
	FogoDaMorte: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Texto5: class extends self.ITextInstance {},
	Texto6: class extends self.ITextInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	Sprite12: class extends self.ISpriteInstance {}
}